server:
  port: 8090

#使用缩进
user:
  name: 姜家伟
  sex: 女
  age: 20
  friends:
      - 小张
      - 小王
      - 小李

#流式(flow)语法
#user: {name: 姜家伟, sex: 男, age: 19}

jasypt:
  encryptor:
    password: 1234567!@#

info:
  username: ENC(VuGJeuivPnkJs35LswyyJw==)
  password: ENC(Iy66r8rXutq0AZ+HN5BbHg==)


# 以--- 开头表示不同的文档，不同的文档又不同的配置
#spring:
#  profiles:
#    active: prod
#
#---
##开发环境
#spring:
#  profiles: dev
#
#server:
#  port: 8080
#
#---
##生产环境
#spring:
#  profiles: prod
#
#server:
#  port: 8090

